### ISSUE TITLE
Provide testing info

### ISSUE THREAD

**Issue by jaygrieves** [s2shape/RedshiftSupplyCollector#1]
Please update the README with how to test this collector, ideally with a run-tests.sh script (which can take a bucket name and credentials as parameters, if necessary).

**Comment by burilovmv** [comment]
Done. I've tried to emulate Redshift with docker image - unfortunately, it's not exactly the same as actual Redshift, some system tables are missing and data types differ. Will require writing different tests for emulator and actual cloud, so I've just added information how to test in the cloud
