### ISSUE TITLE
Setup/run script

### ISSUE THREAD

**Issue by jaygrieves** [s2shape/RedshiftSupplyCollector#3]
Please create a `load-data.sh` script which runs `data.sql` for the provided Redshift cluster.  This will make it a lot easier to get a cluster with loaded data running.

Please also create a `load-data-and-run-test.sh` script which runs `load-data.sh` and `run-tests.sh` with the provided command-line arguments.  This will make it easier to run tests on a newly created cluster.

**Comment by burilovmv** [comment]
Done
